# Generated by Django 2.2.4 on 2020-06-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_detail',
            name='image',
            field=models.FileField(null=True, upload_to='documents/', verbose_name='Upload Image'),
        ),
    ]
