# Generated by Django 2.2.4 on 2020-06-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_register_detail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forming_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Vegetable Name')),
                ('water_contain', models.TextField(max_length=3000, verbose_name='Water Level')),
                ('fertilizer', models.TextField(max_length=3000, verbose_name='Fertilizer')),
                ('soil', models.TextField(max_length=3000, verbose_name='Nature of Soli')),
                ('area', models.TextField(max_length=3000, verbose_name='Fertilize Area')),
                ('season', models.TextField(max_length=3000, verbose_name='Fertilize season')),
                ('others', models.TextField(max_length=3000)),
                ('image', models.FileField(upload_to='farmer/', verbose_name='Upload Image')),
            ],
        ),
    ]
