# Generated by Django 2.2.4 on 2020-06-14 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_forming_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='forming_detail',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Agriculture_Officer_Detail'),
        ),
    ]
