# Generated by Django 2.2.4 on 2020-06-14 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_video_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer_Video_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=3000)),
                ('video', models.FileField(upload_to='documents/', verbose_name='Upload Video')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Agriculture_Officer_Detail')),
            ],
        ),
    ]
