# Generated by Django 3.1.3 on 2020-11-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_officer_video_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, verbose_name='Event Name')),
                ('type_of_event', models.CharField(max_length=100, verbose_name='Event Type')),
                ('date', models.DateField(verbose_name='Event Date')),
                ('place', models.TextField(max_length=3000, verbose_name='Event Place')),
                ('about_event', models.TextField(max_length=3000, verbose_name='About Event')),
                ('address', models.TextField(max_length=3000, verbose_name='Address')),
                ('benefits', models.TextField(max_length=3000, verbose_name='Event Benefit')),
                ('image', models.FileField(upload_to='documents/', verbose_name='Upload Image')),
            ],
        ),
    ]
