# Generated by Django 3.1.3 on 2020-11-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_event_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_scheme', models.CharField(max_length=100, verbose_name='Insurance Scheme')),
                ('year', models.CharField(max_length=100, verbose_name='Year of Insurance')),
                ('insurance_type', models.CharField(max_length=100, verbose_name='Type of Insurance')),
                ('amount', models.CharField(max_length=300, verbose_name='Insurance Amount')),
                ('monthly_amount', models.CharField(max_length=300, verbose_name='Monthly Due Amount')),
                ('insurance_detail', models.TextField(max_length=3000, verbose_name='Insurance Detail')),
                ('company_detail', models.TextField(max_length=3000, verbose_name='Insurance Company Detail')),
                ('documents', models.TextField(max_length=3000, verbose_name='Documents need for Insurance')),
                ('last_date', models.DateField(verbose_name='Last Date to Enquiry')),
                ('insurance_form', models.FileField(upload_to='documents/', verbose_name='Insurance Form')),
            ],
        ),
    ]
