# Generated by Django 3.1.3 on 2020-11-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_insurance_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='forming_detail',
            name='month',
            field=models.CharField(max_length=100, null=True, verbose_name='Month'),
        ),
    ]
