# Generated by Django 3.1.3 on 2020-11-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_forming_detail_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seeds_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_name', models.CharField(max_length=100, verbose_name='Seed Name')),
                ('stock', models.CharField(max_length=3000, verbose_name='Stock')),
                ('district', models.CharField(max_length=3000, verbose_name='district')),
                ('area', models.CharField(max_length=3000, verbose_name='Area')),
                ('image', models.FileField(upload_to='farmer/', verbose_name='Upload Image')),
            ],
        ),
    ]
