# Generated by Django 3.1.3 on 2020-11-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_seeds_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind_speed', models.CharField(max_length=100, verbose_name='Wind Speed')),
                ('temprature', models.CharField(max_length=100, verbose_name='Temprature')),
                ('humutity', models.CharField(max_length=100, verbose_name='Humutity')),
                ('rainfall', models.CharField(max_length=100, verbose_name='Rainfall')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('date', models.DateField(verbose_name='Date')),
                ('chance_of_rain', models.CharField(max_length=100, verbose_name='Chance of Rain')),
                ('image', models.FileField(upload_to='documents/', verbose_name='Upload Image')),
            ],
        ),
    ]
