# Generated by Django 3.1.3 on 2020-12-04 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_ask_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tractor_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('lease', models.CharField(max_length=50)),
                ('feature', models.TextField(max_length=3000)),
                ('image', models.FileField(upload_to='documents/', verbose_name='Upload Image')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('tractor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tractor_detail')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register_detail')),
            ],
        ),
    ]
