from django.urls import path
from . import views
urlpatterns = [
path('',views.home,name="home"),
path('officer_login/',views.officer_login,name="officer_login"),
path('officer_dashboard/',views.officer_dashboard,name="officer_dashboard"),
path('officer_logout/',views.officer_logout,name="officer_logout"),
path('register/',views.register,name="register"),
path('user_login/',views.user_login,name="user_login"),
path('dashboard/',views.dashboard,name="dashboard"),
path('logout/',views.logout,name="logout"),
path('categories/',views.categories,name="categories"),
path('add_product/',views.add_product,name="add_product"),
path('view_product/',views.view_product,name="view_product"),
path('product_edit/<int:pk>/',views.product_edit,name="product_edit"),
path('product_delete/<int:pk>/',views.product_delete,name="product_delete"),
path('view_farmer/',views.view_farmer,name="view_farmer"),
path('veg_product/',views.veg_product,name="veg_product"),
path('add_forming/',views.add_forming,name="add_forming"),
path('forming/',views.forming,name="forming"),
path('delete/<int:pk>/',views.delete,name="delete"),
path('search/',views.search,name="search"),
path('contact/',views.contact,name="contact"),
path('add_video/',views.add_video,name="add_video"),
path('videos/',views.videos,name="videos"),
path('delete_video/<int:pk>/',views.delete_video,name="delete_video"),
path('video_list/',views.video_list,name="video_list"),
path('officer_video/',views.officer_video,name="officer_video"),
path('delete_officer_video/<int:pk>/',views.delete_officer_video,name="delete_officer_video"),
path('add_officer_video/',views.add_officer_video,name="add_officer_video"),
path('event_detail/',views.event_detail,name="event_detail"),
path('insurance_detail/',views.insurance_detail,name="insurance_detail"),
path('seeds_detail/',views.seeds_detail,name="seeds_detail"),
path('weather/',views.weather,name="weather"),
path('question/',views.question,name="question"),
path('view_question/',views.view_question,name="view_question"),
path('view_answer/<int:pk>/',views.view_answer,name="view_answer"),
path('answer/',views.answer,name="answer"),
path('reply/<int:pk>/',views.reply,name="reply"),
path('add_tractor/',views.add_tractor,name="add_tractor"),
path('tractor_edit/<int:pk>/',views.tractor_edit,name="tractor_edit"),
path('view_tractor/',views.view_tractor,name="view_tractor"),
path('tractor_delete/<int:pk>/',views.tractor_delete,name="tractor_delete"),
path('tractors/',views.tractors,name="tractors"),
path('enquiry/<int:pk>/',views.enquiry,name="enquiry"),
path('reject/<int:pk>/',views.reject,name="reject"),
path('enquiry_details/',views.enquiry_details,name="enquiry_details"),
path('accept/<int:pk>/',views.accept,name="accept"),
path('tractor_enquiry/',views.tractor_enquiry,name="tractor_enquiry"),


]


